### ISSUE TITLE
New release for payload 1.x.x

### ISSUE THREAD

**Issue by dominikzogg** [payloadcms/plugin-nested-docs#20]
The last release is 1.0.4 which depends on 0.x.x of this plugin, would be great if you could built and tag the current code as 1.0.5.

**Comment by jacobsfletch** [comment]
@dominikzogg hmm i'm not sure i'm following. The plugin indicated a Payload peer dependency of `"^0.18.5 || ^1.0.0"`: https://github.com/payloadcms/plugin-nested-docs/blob/main/package.json#L28. Is this what you're referring to?

**Comment by dominikzogg** [comment]
@jacobsfletch yes, but if you check the tagged code (and the built one) its 0.x only

**Comment by jacobsfletch** [comment]
@dominikzogg wow good catch, fix incoming 👍

**Comment by jacobsfletch** [comment]
^^ Just released `1.0.5` 🎉

**Comment by dominikzogg** [comment]
@jacobsfletch thanks for fixing. I used payload the first time today, evaluate it as a replacement for strapi. Works great so far.

**Comment by jacobsfletch** [comment]
@dominikzogg very nice! Let me know if you have any questions at all, and if you're not already on our Discord server, here's an invite: https://discord.com/invite/payload
