### ISSUE TITLE
Issue with updating child pages if NOT in defaultLang

### ISSUE THREAD

**Issue by MarvinVrdoljak** [payloadcms/plugin-nested-docs#23]
Hey there, me and my company are about to release our first big Payload project, but we were running in a bigger issue today:
If you edit your parent page, the child pages are not getting the changes if you are not in your defaultLang.

### To reproduce:
**Step 1:** 
- Log in into your demo website and go to pages: https://demo.payloadcms.com/admin/collections/pages

**Step 2:** 
- Create a parent page "Parent Page" in your default language EN
- Create a child page "Child Page" in your default language EN and choose "Parent Page" for your parent
- Change parent page name "Parent Page Changed" and go to overview
- Child page's full title is correct > everything works how it should

![Screenshot 2023-06-23 184940](https://github.com/payloadcms/plugin-nested-docs/assets/25500828/8f39ed85-1c7d-43e4-b233-ddce89839e5f)

**Step 3:**
- Change Language to ES
- Go to your created parent page and type in (translated) title: "Parent Page ES" 
- Go to your created child page and type in (translated) title: "Child Page ES"
- Change parent page name "Parent Page ES Changed" and go to overview
- Child page's full type **did not update** > You need to update/save child pages manually to get the updated parent title. 

![Screenshot 2023-06-23 184847](https://github.com/payloadcms/plugin-nested-docs/assets/25500828/ff0ad73b-9add-4259-887b-4a012e1b91cc)

The title is not even the biggest issue. The fullSlug is not updating either. Our client has like 100 pages and they need to save all child pages if they change the slug or title in the parent pages.
We really love payload and we hope that this issue is getting fixed quite soon. Cheers!

**Comment by jacobsfletch** [comment]
Hey @MarvinVrdoljak thank you for the detailed report here! I think we can get this sorted out for you quickly. I just shared your issue in our Discord to see if anyone has the bandwidth to look into this for you right away, otherwise the Payload team could probably swing it on Monday.

**Comment by MarvinVrdoljak** [comment]
@jacobsfletch Hey hey! Are there any updates yet?

**Comment by puck3000** [comment]
@jacobsfletch hy there! I'm affected by this issue too... a solution would be greatly appreciated.

**Comment by TurtleTT** [comment]
Hey @jacobsfletch are there any updates about that issue? We have the same problem with our project.

**Comment by jacobsfletch** [comment]
@MarvinVrdoljak @puck3000 @TurtleTT Hey everyone! Thank you for all the follow-up here. I'm looking through right now and will post an update shortly 👍

**Comment by jacobsfletch** [comment]
Just released `v1.0.6` with the fix. Give that a shot and let me know how it goes!

**Comment by MarvinVrdoljak** [comment]
@jacobsfletch Looks great. Cheers guys!
