### ISSUE TITLE
Support for multi locale breadcrumbs

### ISSUE THREAD

**Issue by mikemoooo** [payloadcms/plugin-nested-docs#4]
Hey there!

I've tried the plugin and this is working fine for documents that are all in the same language.
However, when using multiple languages the breadcrumbs are updated after every change to the document.

This means that the last updated language is the one that reflects in the breadcrumbs.

Would it be possible to add multi language support to this plugin, so the breadcrumbs can be used for getStaticPaths in NextJS?

**Comment by jacobsfletch** [comment]
Hey @mikemoooo! Yes, this absolutely should be supported. I'm going to mark this is a feature request to get the ball rolling. Feel free to give it a shot in the meantime!

**Comment by mikemoooo** [comment]
Hey @jacobsfletch,
I have it working locally by adding `localized: true` in the `createBreadcrumbsField` function.
If you are adding it in a project that is in use, you need to resave all documents to populate the breadcrumbs.

**Comment by mikemoooo** [comment]
I’ve got it working locally by adding the localized: true value to the
createBredcrumbs function
