### ISSUE TITLE
Update childeren when parent gets new url/parent

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/plugin-nested-docs#6]
At the moment when you have this structure:
home -> SubPage1 -> SubPage2

And update SubPage1 to have no parent, SubPage2 should have this structure:
SubPage1 -> SubPage2

The problem is that SubPage2 has still home inside the breadcrumbs & url structure.
SubPage1 is in this instance is correctly updated to have no parent.

We use this plugin in a large project where we have more than 100 pages under SubPage1
Now we have to hit update on every page when the url structure changed on SubPage1

**Comment by jacobsfletch** [comment]
Hi @matthijs166, ok I'm following here. Right now we recursively same each document down the ancestry tree when one changes, but it sounds like there's a missing condition on the recursion.

**Comment by jacobsfletch** [comment]
Hey @matthijs166 I was not able to recreate this, here's a screen recording doing exactly what you describe. Check it out:

https://user-images.githubusercontent.com/15735305/202036452-839db2ac-24fa-4898-a120-f2abb80a6dbd.mp4

If you want to try it out yourself, the demo database seeds itself now, and I added that grandchild page to that seed, so if you boot the demo app you will get exactly what is shown in my recording.

`cd demo && yarn && yarn dev`

Which version are you running? Try bumping to `1.0.3`.
